version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  app:
    container_name: app
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  worker:
    container_name: worker
    build: .
    # command: celery -A worker.celery worker -l info -Q default,baz # prefork Ejecución en múltiples procesos
    command: celery -A worker.celery worker -B -l info -Q default,baz,schedule -P solo # solo Ejecución en el hilo principal solamente
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A worker.celery flower --port=5555 --basic-auth=admin:admin
    ports:
      - 5556:5555
    environment:
      - FLOWER_UNAUTHENTICATED_API=true
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis
      - worker
